version: '3'

rpc:
  listen: tcp://${RUNNER_RPC_HOST:-127.0.0.1}:${RUNNER_RPC_PORT:-6001}

status:
  address: ${RUNNER_HEALTHCHECK_IP:-127.0.0.1}:${RUNNER_HEALTHCHECK_PORT:-2115}

server:
  command: 'php vendor/bin/rr-worker start'
  relay: pipes

http:
  address: 0.0.0.0:8080
  middleware:
    - gzip
    - static
    - headers
  static:
    dir: public
    forbid:
      - .env
      - .conf
      - .ini
      - .php
      - .htaccess
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 512
